Blast4-request ::= {
  body queue-search {
    program "blastn",
    service "plain",
    queries bioseq-set {
      seq-set {
        seq {
          id {
            local str "Query_155483"
          },
          descr {
            user {
              type str "CFastaReader",
              data {
                {
                  label str "DefLine",
                  data str ">reference=NZ_CP011299.1 position=418509..418608
 description=\""Buchnera aphidicola (Schlechtendalia chinensis) strain SC,
 complete genome\"" - against B. aphidicola except 118110"
                }
              }
            },
            title "reference=NZ_CP011299.1 position=418509..418608
 description=""Buchnera aphidicola (Schlechtendalia chinensis) strain SC,
 complete genome"" - against B. aphidicola except 118110"
          },
          inst {
            repr raw,
            mol dna,
            length 100,
            seq-data ncbi2na '3CCF2C0CFFE285390CFCD3283C7DC1B340003F79F503C703
33'H
          }
        }
      }
    },
    subject database "nr",
    algorithm-options {
      {
        name "EvalueThreshold",
        value cutoff e-value { 1, 10, 1 }
      },
      {
        name "UngappedMode",
        value boolean FALSE
      },
      {
        name "PercentIdentity",
        value real { 0, 10, 0 }
      },
      {
        name "HitlistSize",
        value integer 100
      },
      {
        name "EffectiveSearchSpace",
        value big-integer 0
      },
      {
        name "DbLength",
        value big-integer 0
      },
      {
        name "WindowSize",
        value integer 0
      },
      {
        name "DustFiltering",
        value boolean TRUE
      },
      {
        name "RepeatFiltering",
        value boolean FALSE
      },
      {
        name "MaskAtHash",
        value boolean TRUE
      },
      {
        name "DustFilteringLevel",
        value integer 20
      },
      {
        name "DustFilteringWindow",
        value integer 64
      },
      {
        name "DustFilteringLinker",
        value integer 1
      },
      {
        name "MismatchPenalty",
        value integer -3
      },
      {
        name "MatchReward",
        value integer 2
      },
      {
        name "GapOpeningCost",
        value integer 5
      },
      {
        name "GapExtensionCost",
        value integer 2
      },
      {
        name "StrandOption",
        value strand-type both-strands
      },
      {
        name "WordSize",
        value integer 11
      }
    },
    program-options {
      {
        name "EntrezQuery",
        value string "(txid9 [ORGN]) NOT (txid118110 [ORGN])"
      }
    },
    format-options {
      {
        name "Web_JobTitle",
        value string "reference=NZ_CP011299.1 position=418509..418608..."
      },
      {
        name "Web_OrganismName",
        value string "Buchnera aphidicola (taxid:9)"
      },
      {
        name "Web_ShortQueryAdjust",
        value boolean TRUE
      }
    }
  }
}

